system:
  mode: debug # release
  ip: 127.0.0.1
  port: 8080
db:
  mode: mysql # mysql pgsql sqlite ""
  db_name: rbac_db
  host: 127.0.0.1
  port: 3006
  user: root
  password: 756131502
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 1
  pool_size: 10